cookboard/cookboard/Models/EmentaSemanal.cs
using System;
using System.Collections.Generic;

namespace cookboard.Models
{
    public partial class EmentaSemanal
    {
        public EmentaSemanal()
        {
            EmentaSemanalReceita = new HashSet<EmentaSemanalReceita>();
        }

        public int Id { get; set; }
        public string UtilizadorUsername { get; set; }
        public DateTime DataLancamento { get; set; }

        public virtual Utilizador UtilizadorUsernameNavigation { get; set; }
        public virtual ICollection<EmentaSemanalReceita> EmentaSemanalReceita { get; set; }
    }
}

cookboard/cookboard/Controllers/EmentaSemanalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cookboard.Models;

namespace cookboard.Controllers
{
    public class EmentaSemanalController : Controller
    {
        private readonly cookBoardContext co;
        public EmentaSemanalController(cookBoardContext context)
        {
            //_context = context;
            co = context;
        }

        public string userType(string username)
        {
            var u = (from m in co.Utilizador
                     where (m.Username == username)
                     select m).FirstOrDefault();

            string tipo = u.Tipo;
            return tipo;
        }

        public ActionResult getEmentaSemanal()
        {
            var size = (from m in co.EmentaSemanal select m).ToList().Count;

            List<Receita> receita = (from m in co.EmentaSemanalReceita
                          join n in co.Receita on m.ReceitaId equals n.Id
                          where (m.EmentaSemanalId == size)
                          select n).ToList();
            
            List<string> dias = (from m in co.EmentaSemanalReceita
                          where (m.EmentaSemanalId == size)
                          select m.Dia).ToList();

            var num = dias.Count;

            List<EmentaViewModel> final = new List<EmentaViewModel>();

            for (int i=0; i<num; i++)
            {
                Receita r = receita[i];
                string d = dias[i];

                final.Add(new EmentaViewModel(d, r));
            }

            string username = User.Identity.Name;

            ViewData["Type"] = userType(username);
            return View(final);
        }

        public ActionResult getIngredientes()
        {
            var size = (from m in co.EmentaSemanal select m).ToList().Count;

            var ing = (from m in co.EmentaSemanalReceita
                          join n in co.Receita on m.ReceitaId equals n.Id
                          join ri in co.ReceitaIngrediente on n.Id equals ri.ReceitaId
                          join i in co.Ingrediente on ri.IngredienteId equals i.Id
                          where (m.EmentaSemanalId == size)
                          select i).ToHashSet();

            string username = User.Identity.Name;

            ViewData["Type"] = userType(username);
            return View(ing);
        }

        [HttpGet]
        public ActionResult RegisterEmenta()
        {
            List<Receita> receitas = (from ri in co.Receita
                                      select ri).ToList();

            return View(new RegisterReceitaModel(receitas));
        }

        public void geraReceitaEmentaSemanal(String receitaI, String dia, int idEmenta)
        {
            var receita = (from m in co.Receita where (m.Nome == receitaI) select m).FirstOrDefault();
            EmentaSemanalReceita er = new EmentaSemanalReceita();
            er.EmentaSemanalId = idEmenta;
            er.ReceitaId = receita.Id;
            er.Dia = dia;
            co.EmentaSemanalReceita.Add(er);
            co.SaveChanges();
        }

        [HttpPost]
        public ActionResult RegisterEmenta(DateTime data, String receitaS, String receitaT, String receitaQ, String receitaQuinta, String receitaSexta)
        {
            EmentaSemanal e = new EmentaSemanal();
            co.EmentaSemanal.Add(e);
            e.DataLancamento = data;
            e.UtilizadorUsername = User.Identity.Name;
            co.SaveChanges();
            geraReceitaEmentaSemanal(receitaS, "Segunda-Feira", e.Id);
            geraReceitaEmentaSemanal(receitaT, "Terça-Feira", e.Id);
            geraReceitaEmentaSemanal(receitaQ, "Quarta-Feira", e.Id);
            geraReceitaEmentaSemanal(receitaQuinta, "Quinta-Feira", e.Id);
            geraReceitaEmentaSemanal(receitaSexta, "Sexta-Feira", e.Id);
            return RedirectToAction("Index", "Professor");
        }
    }
}

cookboard/cookboard/Views/EmentaSemanal/RegisterEmenta.cshtml
@model cookboard.Models.RegisterReceitaModel
@{
    ViewBag.Title = "RegisterEmenta";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";
}


<div style="background-repeat: no-repeat; background-size: cover; height: 100vh;" class="registar-clean">
    <form method="post">
        <div style="text-align: center; font-weight: 900; font-size: 18px; padding-bottom: 20px;">Ementa Semanal</div>
        <div class="form-group">
            <input class="form-control" type="text" name="data" placeholder="Data: AAAA-MM-DD" required>
        </div>
 
        
        <div class="form-group dia-receita">
            <label>Segunda-Feira:</label>
            <select name="receitaS">
                <option value="receitaS">
                    Selecione uma receita:
                </option>
                @foreach (var item in Model.Receitas)
                {
                    <option value="@item.Nome">
                        @item.Nome
                    </option>
                }
            </select>
        </div>
        <div class="form-group dia-receita">
            <label>Terça-Feira:</label>
            <select name="receitaT">
                <option value="receitaT">
                    Selecione uma receita:
                </option>
                @foreach (var item in Model.Receitas)
                {
                    <option value="@item.Nome">
                        @item.Nome
                    </option>
                }
            </select>
        </div>
        <div class="form-group dia-receita">
            <label>Quarta-Feira:</label>
            <select name="receitaQ">
                <option value="receitaQ">
                    Selecione uma receita:
                </option>
                @foreach (var item in Model.Receitas)
                {
                    <option value="@item.Nome">
                        @item.Nome
                    </option>
                }
            </select>
        </div>
        <div class="form-group dia-receita">
            <label>Quinta-Feira:</label>
            <select name="receitaQuinta">
                <option value="receitaQuinta">
                    Selecione uma receita:
                </option>
                @foreach (var item in Model.Receitas)
                {
                    <option value="@item.Nome">
                        @item.Nome
                    </option>
                }
            </select>
        </div>
        <div class="form-group dia-receita">
            <label>Sexta-Feira:</label>
            <select name="receitaSexta">
                <option value="receitaSexta">
                    Selecione uma receita:
                </option>
                @foreach (var item in Model.Receitas)
                {
                    <option value="@item.Nome">
                        @item.Nome
                    </option>
                }
            </select>
        </div>



        <div class="form-group"><button class="btn btn-primary btn-block" type="submit" style="background-color:rgb(146,141,142);">Register</button></div>
    </form>
</div>

cookboard/cookboard/Views/EmentaSemanal/getEmentaSemanal.cshtml
@model IEnumerable<cookboard.Models.EmentaViewModel>
@{
    ViewBag.Title = "getEmentaSemanal";
    string currentType = (string)@ViewData["Type"];

    switch (currentType)
    {
        case "Professor":
            Layout = "~/Views/Shared/_LayoutProfessor.cshtml";
            break;
        case "Aluno":
            Layout = "~/Views/Shared/_LayoutAluno.cshtml";
            break;
    }
}


<div class="container">
    <h1 class="my-4">Ementa Semanal</h1>
    <input type="button" class="btn btn-light" value="Lista Ingredientes" onclick="location.href='@Url.Action("getIngredientes","EmentaSemanal")';" />

    @foreach (var item in Model)
    {
        <hr>
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-fluid rounded mb-3 mb-md-0" src="@Html.DisplayFor(modelItem => item.Receita.Imagem)" alt="" style="height:90%;width:90%">
                </a>
            </div>
            <div class="col-md-5">
                <h1>@Html.DisplayFor(modelItem => item.Dia)</h1>
                <h4>@Html.DisplayFor(modelItem => item.Receita.Nome)</h4>
                <p><img src="~/img/star-half-alt-solid.svg" style="width:15px;margin-top:-5px;">&nbsp; Dificuldade: @Html.DisplayFor(modelItem => item.Receita.Dificuldade)</p>
                <p><img src="~/img/clock-regular.svg" style="width:15px;">&nbsp; Tempo: @Html.DisplayFor(modelItem => item.Receita.TempoConfecao)</p>
                <input type="button" class="btn btn-light" value="Consultar" onclick="location.href='@Url.Action("getReceita","Receitas", new { idReceita = item.Receita.Id })';" />
            </div>
        </div>
    }

</div>

cookboard/cookboard/Views/EmentaSemanal/getIngredientes.cshtml
@model IEnumerable<cookboard.Models.Ingrediente>
@{
    ViewBag.Title = "getIngredientes";
    string currentType = (string)@ViewData["Type"];

    switch (currentType)
    {
        case "Professor":
            Layout = "~/Views/Shared/_LayoutProfessor.cshtml";
            break;
        case "Aluno":
            Layout = "~/Views/Shared/_LayoutAluno.cshtml";
            break;
    }
}

<div style="display:flex; justify-content: space-between">
    <h1 style="margin-left: 24px;">
        Lista Ingredientes
    </h1>
    <input style="margin-right: 24px;" type="button" class="btn btn-light" style="float:right;" value="Localizar Ingredientes" onclick="location.href='@Url.Action("getLocalizacao","LocalIngrediente", new { idReceita = 1 })';" />
</div>

<hr>

<div style="margin-left: 24px;">
    @foreach (var item in Model)
    {
        <input type="checkbox"> @Html.DisplayFor(modelItem => item.Nome)
        <hr>
    }
</div>