cookboard/cookboard/Controllers/ProfessorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cookboard.Models;
using cookboard._Shared;
using System.Security.Cryptography;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;


namespace cookboard.Controllers
{
    [Route("[controller]/[action]")]
    public class ProfessorController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

    }
}

cookboard/cookboard/Views/Professor/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";
}
@{
    ViewBag.Title = "Cookboard";
}

<div>
    <div id="myCarousel" class="carousel" data-ride="carousel">
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/img/banner.jpg" style="width:100%;">
            </div>
        </div>
    </div>
    <div style="        background-color: rgb(204, 230, 255);
        color: black;
        padding: 20px;">
        <h3>QUALIDADES DO ASSISTENTE</h3>
    </div>
    <p>


    </p>
    <div style="width: 100%; background-color: white;">
        <div style="width: 90%; background-color: white;">
            <div class="row" style="padding-left: 17%; padding-right:5%">
                <div class="col-sm-4" style="display: flex; flex-direction: column; align-items: center;">
                    <img src="~/img/diploma.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:black;">EDUCATIVO</span></h2>
                </div>
                <div class="col-sm-4" style="display: flex; flex-direction: column; align-items: center;">
                    <img src="~/img/mixer.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:black;">INTERATIVO</span></h2>
                </div>
                <div class="col-sm-4" style="display: flex; flex-direction: column; align-items: center;">
                    <img src="~/img/chef.png" alt="Generic placeholder image" width="100" height="100">
                    <h2><span class="title" style="color:black;">REQUINTADO</span></h2>
                </div>
            </div>
        </div>
    </div>
    <p>


    </p>
    <div style="        background-color: rgb(204, 230, 255);
        color: black;
        padding: 20px;">
        <h3>PORQUÊ NÓS?</h3>
    </div>

    <div class="row featurette" style="width:99%;">
        <div class="col-md-5" style="margin-left:15.4%; margin-top:40px;">

            <p><span class="text-normal">> Assistente preparado para as suas necessidades.</span></p>
            <p><span class="text-normal">> Disponível 24 horas por dia, 7 dias por semana, 365 dias por ano.</span></p>
            <p><span class="text-normal">> Acompanhamento personalizado.</span></p>
            <p><span class="text-normal">> Receitas fáceis de aprender.</span></p>
            <p><span class="text-normal">> Possibilidade de se tornar um melhor profissional.</span></p>
        </div>
    </div>
</div>
    

cookboard/cookboard/Views/Professor/criaEmenta.cshtml
@model cookboard.Models.Utilizador
@{
    ViewBag.Title = "criaEmenta";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";

}
<h1> Criar Ementa Semanal</h1>

<div class="row">
    <div class="col-12">
        <div class="register-photo">
            <div class="registar-clean" style="background-size:cover;">
                <form method="post">
                    <h1 class="text-center">Ementa Semanal</h1>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Segunda-Feira</span>
                        </div>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Selecionar Receita</label>
                        </div>
                    </div>
                    <p>


                    </p>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Terça-Feira  </span>
                        </div>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Selecionar Receita</label>
                        </div>
                    </div>
                    <p>


                    </p>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Quarta-Feira </span>
                        </div>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Selecionar Receita</label>
                        </div>
                    </div>
                    <p>


                    </p>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Quinta-Feira </span>
                        </div>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Selecionar Receita</label>
                        </div>
                    </div>
                    <p>


                    </p>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupFileAddon01">Sexta-Feira  </span>
                        </div>
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Selecionar Receita</label>
                        </div>
                    </div>
                    <div class="form-group"><button class="btn btn-primary btn-block" type="submit" style="background-color:rgb(146,141,142);">Guardar</button></div>
                </form>
            </div>
        </div>
    </div>
</div> 

cookboard/cookboard/Views/Professor/editarP.cshtml
@model cookboard.Models.Utilizador
@{
    ViewBag.Title = "editarP";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";

}

<div class="container">
    <h1>Editar Perfil</h1>
    <hr>
    <div class="row">
        <!-- left column -->
        <div class="col-md-3">
            <div class="text-center">
                <img src="//placehold.it/100" class="avatar img-circle" alt="avatar">
                <h6>Upload a different photo...</h6>

                <input type="file" class="form-control">
            </div>
        </div>

        <!-- edit form column -->
        <div class="col-md-9 personal-info">
            <div class="alert alert-info alert-dismissable">
                <a class="panel-close close" data-dismiss="alert">×</a>
                <i class="fa fa-coffee"></i>
                This is an <strong>.alert</strong>. Use this to show important messages to the user.
            </div>
            <h3>Informação Pessoal</h3>


            <div class="form-group">
                <label class="col-lg-3 control-label">Nome:</label>
                <div class="col-lg-8">
                    <input class="form-control" type="text" value="Jane">
                </div>
            </div>
            <div class="form-group">
                <label class="col-lg-3 control-label">Email:</label>
                <div class="col-lg-8">
                    <input class="form-control" type="text" value="janesemail@gmail.com">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">Password:</label>
                <div class="col-md-8">
                    <input class="form-control" type="password" value="11111122333">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label">Confirm password:</label>
                <div class="col-md-8">
                    <input class="form-control" type="password" value="11111122333">
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-3 control-label"></label>
                <div class="col-md-8">
                    <input type="button" class="btn btn-primary" value="Save Changes">
                    <span></span>
                    <input type="reset" class="btn btn-default" value="Cancel">
                </div>
            </div>

        </div>
    </div>
</div>

cookboard/cookboard/Views/Professor/getEmentaSemanal.cshtml
@model IEnumerable<cookboard.Models.EmentaViewModel>

@{


    ViewBag.Title = "getEmentaSemanal";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";


}

<div class="container">
    <h1 class="my-4">Ementa Semanal</h1>
    <input type="button" class="btn btn-light" value="Lista Ingredientes" onclick="location.href='@Url.Action("getIngredientes","Professor")';" />

    @foreach (var item in Model)
    {
        <hr>
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-fluid rounded mb-3 mb-md-0" src="@Html.DisplayFor(modelItem => item.Receita.Imagem)" alt="" style="height:90%;width:90%">
                </a>
            </div>
            <div class="col-md-5">
                <h1>@Html.DisplayFor(modelItem => item.Dia)</h1>
                <h4>@Html.DisplayFor(modelItem => item.Receita.Nome)</h4>
                <p><img src="~/img/star-half-alt-solid.svg" style="width:15px;margin-top:-5px;">&nbsp; Dificuldade: @Html.DisplayFor(modelItem => item.Receita.Dificuldade)</p>
                <p><img src="~/img/clock-regular.svg" style="width:15px;">&nbsp; Tempo: @Html.DisplayFor(modelItem => item.Receita.TempoConfecao)</p>
                <input type="button" class="btn btn-light" value="Consultar" onclick="location.href='@Url.Action("getReceita","Receitas", new { idReceita = item.Receita.Id })';" />
            </div>
        </div>
    }

</div>

cookboard/cookboard/Views/Professor/getFavoritos.cshtml
@model IEnumerable<cookboard.Models.Receita>
@{
    ViewBag.Title = "getFavoritos";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";

}

<h1>Receitas Favoritas</h1>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dificuldade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TempoConfecao)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dificuldade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempoConfecao)
            </td>
            <td>
                @Html.ActionLink("Consultar", "Consultar", new { idReceita = item.Nome })
            </td>
        </tr>
    }
</table>

cookboard/cookboard/Views/Professor/getHistorico.cshtml
@model IEnumerable<cookboard.Models.Receita>

@{
    ViewBag.Title = "getHistorico";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";

}
<h1>Histórico Receitas</h1>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Dificuldade)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TempoConfecao)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Dificuldade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TempoConfecao)
            </td>
            <td>
                @Html.ActionLink("Consultar", "Consultar", new { idReceita = item.Nome })
            </td>
        </tr>
    }
</table>

cookboard/cookboard/Views/Professor/getIngredientes.cshtml
@model IEnumerable<cookboard.Models.Ingrediente>
@{
    Layout = "~/Views/Shared/_LayoutLogin.cshtml";
    ViewData["Title"] = "getIngredientes";
}

<h1>
    Lista Ingredientes <input type="button" class="btn btn-light" style="float:right;" value="Localizar Ingredientes" onclick="location.href='@Url.Action("getLocalizacao","LocalIngrediente", new { idReceita = 1 })';" />
</h1>

<hr>

@foreach (var item in Model)
{
   <input type="checkbox"> @Html.DisplayFor(modelItem => item.Nome)
   <br>
}

cookboard/cookboard/Views/Professor/getReceitas.cshtml
@model IEnumerable<cookboard.Models.Receita>
@{
    ViewBag.Title = "getReceitas";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";

}

<section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests">
    <div class="my-auto">
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-sm-6 text-center mb-4">
                    <a href='@Url.Action("getReceita","Receitas", new { idReceita = item.Id })'>
                    <img class="img-fluid3 d-block mx-auto" src="@Html.DisplayFor(modelItem => item.Imagem)" alt="" style="width:320px; height:180px; border-radius: 5px;">
                    <h3>@Html.DisplayFor(modelItem => item.Nome)</h3>
                    </a>
                    <p class="description"><img src="~/img/star-half-alt-solid.svg" style="width:15px;margin-top:-5px;">&nbsp; Dificuldade: @Html.DisplayFor(modelItem => item.Dificuldade) &nbsp;<img src="~/img/clock-regular.svg" style="width:15px;">Tempo: @Html.DisplayFor(modelItem => item.TempoConfecao)<br></p>
                </div>
            }
            </div>
        </div>
    </section>

cookboard/cookboard/Views/Professor/getUsers.cshtml
@model IEnumerable<cookboard.Models.Utilizador>
@{
    ViewBag.Title = "getUsers";
    Layout = "~/Views/Shared/_LayoutAluno.cshtml";

}

<h1>getUsers</h1>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.ActionLink("Consultar", "Consultar", new { idServico = item.Nome })
            </td>
        </tr>
    }
</table>

cookboard/cookboard/Views/Professor/registaReceita.cshtml
@model cookboard.Models.Utilizador
@{
    ViewBag.Title = "registaRecita";
    Layout = "~/Views/Shared/_LayoutProfessor.cshtml";

}
<div class="row">
    <div class="col-12">
        <div class="register-photo">
            <div class="registar-clean" style="background-size:cover;">
                <form method="post">
                    <h1 class="text-center">Registar Receita</h1>
                    <div class="form-group"><input class="form-control" type="text" name="nome" placeholder="Nome" required></div>
                    <div class="form-group"><input class="form-control" type="time" name="tempo" placeholder="Tempo de Confeção" required></div>
                    <div class="form-group"><input class="form-control" type="text" name="porcao" placeholder="Porções" required></div>
                    <div class="form-group"><input class="form-control" type="text" name="dificuldade" placeholder="Dificuldade" required></div>
                    <div class="form-group"><input class="form-control" type="text" name="info" placeholder="Informação Nutricional" required></div>
                    <div class="form-group"><input class="form-control" type="text" name="descricao" placeholder="Descrição" required></div>
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" id="inputGroupFile01"
                                   aria-describedby="inputGroupFileAddon01">
                            <label class="custom-file-label" for="inputGroupFile01">Escolher Ficheiro</label>
                        </div>
                    </div>
                    <div class="form-group"><button class="btn btn-primary btn-block" type="submit" style="background-color:rgb(146,141,142);">Guardar</button></div>
                </form>
            </div>
        </div>
    </div>
</div>