cookboard/cookboard/Models/Receita.cs
using System;
using System.Collections.Generic;

namespace cookboard.Models
{
    public partial class Receita
    {
        public Receita()
        {
            Avaliacao = new HashSet<Avaliacao>();
            EmentaSemanalReceita = new HashSet<EmentaSemanalReceita>();
            ReceitaIngrediente = new HashSet<ReceitaIngrediente>();
            ReceitaReceitaAuxiliar = new HashSet<ReceitaReceitaAuxiliar>();
            UtilizadorReceita = new HashSet<UtilizadorReceita>();
        }

        public int Id { get; set; }
        public string Nome { get; set; }
        public int Porcao { get; set; }
        public string Imagem { get; set; }
        public string InfoNutricional { get; set; }
        public string Dificuldade { get; set; }
        public string Descricao { get; set; }
        public string TempoConfecao { get; set; }
        public string UtilizadorUsername { get; set; }

        public virtual Utilizador UtilizadorUsernameNavigation { get; set; }
        public virtual ICollection<Avaliacao> Avaliacao { get; set; }
        public virtual ICollection<EmentaSemanalReceita> EmentaSemanalReceita { get; set; }
        public virtual ICollection<ReceitaIngrediente> ReceitaIngrediente { get; set; }
        public virtual ICollection<ReceitaReceitaAuxiliar> ReceitaReceitaAuxiliar { get; set; }
        public virtual ICollection<UtilizadorReceita> UtilizadorReceita { get; set; }
    }
}

cookboard/cookboard/Models/ReceitaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace cookboard.Models
{
    public class ReceitaViewModel
    {
        public ReceitaViewModel(Receita receita, List<IngredienteViewModel> ingredientes)
        {
            Receita = receita;
            Ingredientes = ingredientes;
        }

        public Receita Receita { get; set; }
        public List<IngredienteViewModel> Ingredientes { get; set; }
    }
}

cookboard/cookboard/Controllers/ReceitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using cookboard.Models;

namespace cookboard.Controllers
{
    public class ReceitasController : Controller
    {
        private readonly cookBoardContext co;
        public ReceitasController(cookBoardContext context)
        {
            //_context = context;
            co = context;
        }

        public string userType(string username)
        {
            var u = (from m in co.Utilizador
                     where (m.Username == username)
                     select m).FirstOrDefault();

            string tipo = u.Tipo;
            return tipo;
        }

        public ActionResult getReceitas()
        {
            var receitas = (from m in co.Receita select m);

            List<Receita> lista = receitas.ToList<Receita>();

            string username = User.Identity.Name;

            ViewData["Type"] = userType(username);
            return View(lista);
        }

        public ActionResult getReceita(int idReceita)
        {

            List<Ingrediente> ing = (from ri in co.ReceitaIngrediente 
                                   join i in co.Ingrediente on ri.IngredienteId equals i.Id
                                   where (ri.ReceitaId == idReceita)
                                   select i).ToList();

            List<string> quant = (from ri in co.ReceitaIngrediente
                                  where (ri.ReceitaId == idReceita)
                                  select ri.Quantidade).ToList();

            List<IngredienteViewModel> final = new List<IngredienteViewModel>();
            int num = ing.Count();

            for (int i = 0; i < num; i++)
            {
                Ingrediente ingrediente = ing[i];
                string quantidade = quant[i];

                final.Add(new IngredienteViewModel(quantidade, ingrediente));
            }

            Receita rec = (from n in co.Receita
                       where (n.Id == idReceita)
                       select n).Single();

            string username = User.Identity.Name;

            ViewData["Type"] = userType(username);
            return View(new ReceitaViewModel(rec, final));
        }

        public ActionResult getPassos(int idReceita)
        {
            Receita rec = (from n in co.Receita
                           where (n.Id == idReceita)
                           select n).Single();

            List<ReceitaReceitaAuxiliar> ajudas = (from ri in co.ReceitaReceitaAuxiliar
                                                where (ri.ReceitaId == idReceita)
                                                select ri).ToList();

            List<PassosViewModel> passos = new List<PassosViewModel>();
            string[] words = rec.Descricao.Split('.');
            int tam = words.Length;

            for(int j=0; j<tam-1; j++)
            {
                string type;
                int idAux = -1;
                if (j == 0) type = "primeiro";
                else if (j == tam - 2) type = "ultimo";
                else type = "intermedio";
                foreach(var aux in ajudas)
                {
                    if(aux.Passo == j + 1)
                    {
                        int id = aux.ReceitaAuxiliarId;
                        Receita r = (from n in co.Receita
                                     where (n.Id == id)
                                     select n).Single();
                        idAux = r.Id;
                    }
                }
                passos.Add(new PassosViewModel(j + 1, words[j], j + 2, j, type, idAux, idReceita, -1));
            }

            string username = User.Identity.Name;

            ViewData["Type"] = userType(username);
            return View(passos);
        }

        public ActionResult getPassosAuxiliar(int idReceita, int idReceitaInit)
        {
            Receita rec = (from n in co.Receita
                           where (n.Id == idReceita)
                           select n).Single();

            List<ReceitaReceitaAuxiliar> ajudas = (from ri in co.ReceitaReceitaAuxiliar
                                                   where (ri.ReceitaId == idReceita)
                                                   select ri).ToList();

            List<PassosViewModel> passos = new List<PassosViewModel>();
            string[] words = rec.Descricao.Split('.');
            int tam = words.Length;

            for (int j = 0; j < tam - 1; j++)
            {
                string type;
                int idAux = -1;
                if (j == 0) type = "primeiro";
                else if (j == tam - 2) type = "ultimo";
                else type = "intermedio";
                foreach (var aux in ajudas)
                {
                    if (aux.Passo == j + 1)
                    {
                        int id = aux.ReceitaAuxiliarId;
                        Receita r = (from n in co.Receita
                                     where (n.Id == id)
                                     select n).Single();
                        idAux = r.Id;
                    }
                }
                passos.Add(new PassosViewModel(j + 1, words[j], j + 2, j, type, idAux, idReceita, idReceitaInit));
            }

            string username = User.Identity.Name;

            ViewData["Type"] = userType(username);
            return View(passos);
        }

        [HttpGet]
        public IActionResult RegisterReceita()
        {
            List<Receita> receitas = (from ri in co.Receita
                                      select ri).ToList();
            string username = User.Identity.Name;
            ViewData["Type"] = userType(username);
            return View(new RegisterReceitaModel(receitas));
        }

        public bool registerIngrediente(int receitaId, string ingrediente)
        {
            string[] words = ingrediente.Split('.');
            foreach (var word in words)
            {
                string[] info = word.Split("-");
                if (info.Length > 1)
                {
                    int id;
                    var Ingrediente = (from m in co.Ingrediente where (info[0] == m.Nome) select m).FirstOrDefault();
                    if (Ingrediente == null)
                    {
                        Ingrediente ing = new Ingrediente();
                        ing.Nome = info[0];
                        co.Ingrediente.Add(ing);
                        co.SaveChanges();
                        id = ing.Id;
                    }
                    else id = Ingrediente.Id;
                    ReceitaIngrediente ri = new ReceitaIngrediente();
                    ri.ReceitaId = receitaId;
                    ri.IngredienteId = id;
                    ri.Quantidade = info[1];
                    co.ReceitaIngrediente.Add(ri);
                    co.SaveChanges();
                }
            }

            return true;
        }

        public bool registerReceita(Receita receita, string ingrediente, string receitaAux, int passo)
        {
            string username = User.Identity.Name;
            receita.UtilizadorUsername = username;
            co.Receita.Add(receita);
            co.SaveChanges();
            if (!receitaAux.Equals("receitaAux"))
            {
                ReceitaAuxiliar r = new ReceitaAuxiliar();
                var re = (from m in co.Receita where m.Nome == receitaAux select m).FirstOrDefault();
                r.Id = re.Id;
                co.ReceitaAuxiliar.Add(r);
                co.SaveChanges();
                ReceitaReceitaAuxiliar ra = new ReceitaReceitaAuxiliar();
                ra.Passo = passo;
                ra.ReceitaId = receita.Id;
                ra.ReceitaAuxiliarId = re.Id;
                co.ReceitaReceitaAuxiliar.Add(ra);
                co.SaveChanges();
            }
            registerIngrediente(receita.Id, ingrediente);
            ViewData["Type"] = userType(username);
            return true;
        }

        [HttpPost]
        public IActionResult RegisterReceita([Bind] Receita receita, string ingrediente, string receitaAux, int passo)
        {
            bool RegistrationStatus = registerReceita(receita, ingrediente, receitaAux, passo);
            string username = User.Identity.Name;
            if (RegistrationStatus)
            {
                ModelState.Clear();
            }
            ViewData["Type"] = userType(username);
            return View();
        }

        [HttpGet]
        public ActionResult getAvaliacao(int idReceita)
        {
            string username = User.Identity.Name;

            var rec = (from n in co.Receita
                       where (n.Id == idReceita)
                       select n).Single();

            var ure = (from n in co.UtilizadorReceita
                       where (n.ReceitaId == idReceita && n.UtilizadorUsername == username)
                       select n).FirstOrDefault();

            if (ure == null)
            {
                UtilizadorReceita ur = new UtilizadorReceita();
                ur.Favorito = 0;
                ur.ReceitaId = idReceita;
                ur.UtilizadorUsername = username;
                co.UtilizadorReceita.Add(ur);
                co.SaveChanges();
            }
            ViewData["Type"] = userType(username);
            return View(rec);
        }

        [HttpPost]
        public ActionResult avaliar(string comentario, int estrelas, int idReceita)
        {
            var rec = (from n in co.Receita
                       where (n.Id == idReceita)
                       select n).Single();

            int id = idReceita;

            Avaliacao a = new Avaliacao();
            a.Comentario = comentario;
            a.Estrela = estrelas;
            a.ReceitaId = idReceita;
            co.Avaliacao.Add(a);
            co.SaveChanges();
            return RedirectToAction("getAvaliacao", new { idReceita = idReceita });

cookboard/cookboard/Views/Receitas/getAvaliacao.cshtml
@{
    string currentType = (string)@ViewData["Type"];

    switch (currentType)
    {
        case "Professor":
            Layout = "~/Views/Shared/_LayoutProfessor.cshtml";
            break;
        case "Aluno":
            Layout = "~/Views/Shared/_LayoutAluno.cshtml";
            break;
    }
}

<div class="row" style="margin: 0px 24px;">
    <div class="col-md-6" style="margin-top: 20px">
        <h3>Secção de Comentários</h3>
        <hr style="border-color: white;">
        @{ using (Html.BeginForm("avaliar", "Receitas", FormMethod.Post))
            {
                <input type="text" placeholder='Comentário' style="font-size:1rem; overflow:auto; width: 400px;" name="comentario" id="nome" required />
                <input type="text" name="idReceita" value="@Model.Id" required hidden />
                <input type="submit" value="Avaliar" class="btn btn-light" />
            }
        }
        <hr style="border-color: white;">
        <h3>Avalie a receita</h3>
        <input type="tel" list="estrelas" placeholder='⭐' style="float:left; width: 47px; margin-top:5px; text-align: center" name="estrelas" required>
        <datalist id="estrelas">
            <option value="1">⭐</option>
            <option value="2">⭐⭐</option>
            <option value="3">⭐⭐⭐</option>
            <option value="4">⭐⭐⭐⭐</option>
            <option value="5">⭐⭐⭐⭐⭐</option>
        </datalist>
        <input type="button" style="margin-left: 360px" class="btn btn-light" value="Adicionar Favorito" onclick="location.href='@Url.Action("addFavorito", "Receitas", new { idReceita = Model.Id, favorito = true })'" ;" />
    </div>
</div>

cookboard/cookboard/Views/Receitas/getPassos.cshtml
@model IEnumerable<cookboard.Models.PassosViewModel>
@{
    ViewData["Title"] = "getPassos";
    Layout = "~/Views/Shared/_LayoutPassos.cshtml";

}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            @foreach (var item in Model)
            {
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#@Html.DisplayFor(modelItem => item.NumPasso)">Passo @Html.DisplayFor(modelItem => item.NumPasso)</a>
                </li>
            }
        </ul>
    </div>
</nav>

<div class="container-fluid p-0">

    @foreach (var item in Model)
    {
        if (item.Type == "ultimo")
        {
            if (item.Auxiliar != -1)
            {
                <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                    <div class="w-100">
                        <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                    </div>
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Terminar" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Html.Raw(@Url.Action("getPassosAuxiliar","Receitas", new { idReceita = item.Auxiliar, idReceitaInit = item.IdReceita }))'" ;" />
                </section>
            }
            else
            {
                <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                    <div class="w-100">
                        <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                    </div>
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Terminar" onclick="location.href='@Url.Action("getAvaliacao","Receitas",new { idReceita = item.IdReceita })'" ;" />
                </section>
            }
        }
        else
        {
            if (item.Type == "primeiro")
            {
                if (item.Auxiliar != -1)
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Html.Raw(@Url.Action("getPassosAuxiliar","Receitas", new { idReceita = item.Auxiliar, idReceitaInit = item.IdReceita }))'" ;" />
                    </section>
                }
                else
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                    </section>
                }
            }
            else
            {
                if (item.Auxiliar != -1)
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Html.Raw(@Url.Action("getPassosAuxiliar","Receitas", new { idReceita = item.Auxiliar, idReceitaInit = item.IdReceita }))'" ;" />
                    </section>
                }
                else
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                    <div class="w-100">
                        <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                    </div>
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                    <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                </section>
                }
            }
        }

        <hr class="m-0">
    }

</div>

cookboard/cookboard/Views/Receitas/getPassosAuxiliar.cshtml
@model IEnumerable<cookboard.Models.PassosViewModel>
@{
    ViewData["Title"] = "getPassosAuxiliar";
    Layout = "~/Views/Shared/_LayoutPassos.cshtml";

}

<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" href="#page-top">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            @foreach (var item in Model)
            {
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#@Html.DisplayFor(modelItem => item.NumPasso)">Passo @Html.DisplayFor(modelItem => item.NumPasso)</a>
                </li>
            }
        </ul>
    </div>
</nav>

<div class="container-fluid p-0">

    @foreach (var item in Model)
    {
        if (item.Type == "ultimo")
        {
            if (item.Auxiliar != -1)
            {
                if (item.IdReceitaInit != -1)
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Terminar" onclick="location.href='@Url.Action("getPassos", "Receitas", new { idReceita = item.IdReceitaInit })'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Url.Action("getPassos", "Receitas", new { idReceita = item.Auxiliar })'" ;" />
                    </section>
                }
                else
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Terminar" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Url.Action("getPassos", "Receitas", new { idReceita = item.Auxiliar })'" ;" />
                    </section>
                }
            }
            else
            {
                if (item.IdReceitaInit != -1)
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Terminar" onclick="location.href='@Url.Action("getPassos", "Receitas", new { idReceita = item.IdReceitaInit })'" ;" />
                    </section>
                }
                else
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Terminar" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                    </section>
                }
            }
        }
        else
        {
            if (item.Type == "primeiro")
            {
                if (item.Auxiliar != -1)
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Url.Action("getPassos","Receitas", new { idReceita = item.Auxiliar })'" ;" />
                    </section>
                }
                else
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                    </section>
                }
            }
            else
            {
                if (item.Auxiliar != -1)
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Ajuda" onclick="location.href='@Url.Action("getPassos","Receitas", new { idReceita = item.Auxiliar, idReceitaInit = item.IdReceita })'" ;" />
                    </section>
                }
                else
                {
                    <section class="resume-section p-3 p-lg-5 d-flex align-items-center" id="@Html.DisplayFor(modelItem => item.NumPasso)">
                        <div class="w-100">
                            <h6>@Html.DisplayFor(modelItem => item.Passo)</h6>
                        </div>
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Anterior" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoAnt)'" ;" />
                        <input type="button" class="btn btn-light" style="float:right; margin-top:50%;" value="Proximo" onclick="location.href='#@Html.DisplayFor(modelItem => item.NumPassoProx)'" ;" />
                    </section>
                }
            }
        }

        <hr class="m-0">
    }

</div>

cookboard/cookboard/Views/Receitas/getReceita.cshtml
@model cookboard.Models.ReceitaViewModel
@{
    ViewBag.Title = "getReceita";
    string currentType = (string)@ViewData["Type"];

    switch (currentType)
    {
        case "Professor":
            Layout = "~/Views/Shared/_LayoutProfessor.cshtml";
            break;
        case "Aluno":
            Layout = "~/Views/Shared/_LayoutAluno.cshtml";
            break;
    }
}


<div class="container">

    <!-- Portfolio Item Heading -->
    <h1 class="my-4">
        @Html.DisplayFor(modelItem => Model.Receita.Nome)
        <input type="button" class="btn btn-light" style="float:right;" value="Iniciar Receita" onclick="location.href='@Url.Action("getPassos","Receitas", new { idReceita = Model.Receita.Id })';" />
    </h1>

    <!-- Portfolio Item Row -->
    <div class="row">

        <div class="col-md-6">
            <div class="receita" style="margin-left:20px;">
                <img class="img-fluid" src="@Html.DisplayFor(modelItem => Model.Receita.Imagem)" style="height:290px;width:480px;border-radius: 5px;" alt="">
            </div>
            <ul style="list-style-type: none; margin-top: 10px;">
                <li><img src="~/img/clock-regular.svg" style="width:15px;"> Tempo de confeção: @Html.DisplayFor(modelItem => Model.Receita.TempoConfecao)</li>
                <li><img src="~/img/star-half-alt-solid.svg" style="width:15px;margin-top:-5px;"> Dificuldade: @Html.DisplayFor(modelItem => Model.Receita.Dificuldade)</li>
                <li><img src="~/img/utensils-solid.svg" style="width:13px;margin-top:-5px;"> Porção: @Html.DisplayFor(modelItem => Model.Receita.Porcao)</li>
                <hr>
                <h6><img src="~/img/balance-scale-solid.svg" style="width:15px;"> Informação Nutricional</h6>
                <li>@Html.DisplayFor(modelItem => Model.Receita.InfoNutricional)</li>
            </ul>
        </div>

        <div class="col-md-6">
            <div class="ing" style="margin-left:40px;">
                <h3 class="my-3">Ingredientes</h3>

                @foreach (var item in Model.Ingredientes)
                {
                    <input type="checkbox"> @Html.DisplayFor(modelItem => item.Quantidade) @Html.DisplayFor(modelItem => item.Ingrediente.Nome)<br>
                }
                <input type="button" class="btn btn-light" style="float:right;" value="Localizar Ingredientes" onclick="location.href='@Url.Action("getLocalizacao","LocalIngrediente", new { idReceita = Model.Receita.Id })';" />
            </div>
        </div>
    </div>

</div>